//! `no-watermark` — desktop interface.
//!
//! A single window: paste on the left, clean text on the right, and an
//! explanation of everything that was found underneath. The interface follows
//! the system language (English or Italian) and can be switched at runtime.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod theme;

use app::App;

const ICON_PNG: &[u8] = include_bytes!("../../../assets/icon-256.png");

fn main() -> eframe::Result<()> {
    let icon = eframe::icon_data::from_png_bytes(ICON_PNG)
        .expect("the bundled icon is generated by packaging/make_icons.py");

    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title("no-watermark")
            .with_inner_size([1120.0, 760.0])
            .with_min_inner_size([760.0, 520.0])
            .with_icon(icon),
        ..Default::default()
    };

    eframe::run_native(
        "no-watermark",
        options,
        Box::new(|cc| Ok(Box::new(App::new(cc)))),
    )
}
